version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: fix(deps)
    groups:
      dev-dependencies: